In [2]:
import pandas as pd
from scipy.stats import ttest_ind, ttest_ind_from_stats

import numpy as np
np.random.seed(12345678)

In [3]:
data = pd.read_csv("https://raw.githubusercontent.com/mahat/TtestExample/master/dataset/MPG_DataSet.csv", sep=';')

In [4]:
data.head()

USA  Japan
0   18     24
1   15     27
2   18     27
3   16     25
4   17     31

In [5]:
data.shape

(249, 2)

In [9]:
data.isnull().sum()

USA      0
Japan    0
dtype: int64

In [14]:
pd.value_counts('Japan')

Japan    5
dtype: int64

In [21]:
data.Japan.unique()

array([  24,   27,   25,   31,   35,   19,   28,   23,   20,   22,   18,
         32,   26,   29,   33,   34,   30,   39,   36,   21,   38,   37,
         47,   41,   45, -999], dtype=int64)

In [23]:
data.dtypes

USA      int64
Japan    int64
dtype: object

In [28]:
usa=data['USA'].values

In [33]:
jap=data['Japan']
jap_val=jap[jap != -999]

In [34]:
jap_val

0     24
1     27
2     27
3     25
4     31
      ..
74    34
75    38
76    32
77    38
78    32
Name: Japan, Length: 79, dtype: int64

In [44]:
usa.mean()

20.14457831325301

In [45]:
jap_val.mean()

30.481012658227847

In [56]:
usa.var()

40.98311317559395

In [57]:
jap_val.var()

37.30412203829926

In [55]:
print(len(jap_val))
print(len(usa))

79
249


In [66]:
significance = 0.05
t_stats, p_val = ttest_ind(usa,jap_val,equal_var=False)
print(t_stats, p_val)

# pvalue is < 0.05 , so reject null hypothesis

#which concludes that the means of the two population are not same

-12.946273274932006 1.5708547842954538e-25


In [36]:
Us=data['USA'].values
Us

array([18, 15, 18, 16, 17, 15, 14, 14, 14, 15, 15, 14, 15, 14, 22, 18, 21,
       21, 10, 10, 11,  9, 28, 25, 19, 16, 17, 19, 18, 14, 14, 14, 14, 12,
       13, 13, 18, 22, 19, 18, 23, 26, 25, 20, 21, 13, 14, 15, 14, 17, 11,
       13, 12, 13, 15, 13, 13, 14, 22, 28, 13, 14, 13, 14, 15, 12, 13, 13,
       14, 13, 12, 13, 18, 16, 18, 18, 23, 11, 12, 13, 12, 18, 21, 19, 21,
       15, 16, 15, 11, 20, 21, 19, 15, 26, 25, 16, 16, 18, 16, 13, 14, 14,
       14, 28, 19, 18, 15, 15, 16, 15, 16, 14, 17, 16, 15, 18, 21, 20, 13,
       23, 20, 23, 18, 19, 25, 26, 18, 16, 16, 15, 22, 22, 24, 23, 29, 25,
       20, 18, 19, 18, 27, 13, 17, 13, 13, 13, 30, 26, 18, 17, 16, 15, 18,
       21, 19, 19, 16, 16, 16, 16, 25, 26, 31, 34, 36, 20, 19, 20, 19, 21,
       20, 25, 21, 19, 21, 21, 19, 18, 19, 18, 18, 18, 30, 31, 23, 24, 22,
       20, 22, 20, 21, 17, 18, 17, 18, 17, 16, 19, 19, 36, 27, 23, 24, 34,
       35, 28, 29, 27, 34, 32, 28, 26, 24, 19, 28, 24, 27, 27, 26, 24, 30,
       39, 35, 34, 30, 22

In [41]:
jp=data["Japan"]
jpp=jp[jp != -999]
jpp.values

array([24, 27, 27, 25, 31, 35, 24, 19, 28, 23, 27, 20, 22, 18, 20, 31, 32,
       31, 32, 24, 26, 29, 24, 24, 33, 33, 32, 28, 19, 32, 34, 26, 30, 22,
       22, 33, 39, 36, 28, 27, 21, 24, 30, 34, 32, 38, 37, 30, 31, 37, 32,
       47, 41, 45, 34, 33, 24, 32, 39, 35, 32, 37, 38, 34, 34, 32, 33, 32,
       25, 24, 37, 31, 36, 36, 34, 38, 32, 38, 32], dtype=int64)